### ISSUE TITLE
Add option to remove all leading whitespace

### ISSUE THREAD

**Issue by fpg1503** [barbosa/clorox#18]
I really enjoy Clorox and we even enforce it's usage using the [danger plugin](https://github.com/barbosa/danger-clorox), however I have some files with trailing whitespaces/newlines before the actual code so when I run it these files start being flagged as with errors due to  the [SwiftLint Leading Whitespace rule](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/LeadingWhitespaceRule.swift).

How do you feel about adding an option to enable the complete removal of leading whitespace?

Thanks for the awesome job so far! 🎉

**Comment by barbosa** [comment]
Hey @fpg1503 
I just saw your message. Sorry about taking so long. I think my GitHub notifications were off.

Sure. That makes total sense!
I'll have some free time next week and I can implement that. Unless you want to do it.

Thank you!

**Comment by barbosa** [comment]
I've add the option `--trim` (defaults to `True`) to the command.

Thanks once again, @fpg1503 !
